config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :user do get "/registrations/show" => "registrations_controller"
  end
  root to: "home#index" 

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable
  
  validates :name, :presence => true
  validates :role, :presence => true

  def ceo?
    self.role == "ceo"
  end

  def employee?
    self.role != "ceo"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:role, :name, :email, :password, :password_confirmation)}
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:id, :name, :salary, :rating,:department)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def index
    if current_user.present?
      if current_user.ceo?
        #@tests = Test.all
        #@report_tests = StudentTest.select(:test_id).uniq
        @employees = Employee.all
        render "ceo_index"
      elsif current_user.employee?
        #
        @employees = Employee.all
        #@current_test_id = Test.find_by_status("activated")
        #if Test.find_by_status("activated") and !StudentTest.where(status: "completed", user_id: current_user.id, test_id: @current_test_id).present?
        #  @current_test = Test.find(@current_test_id)
        #else
        #  @current_test_id = nil
        #end
        #@student_completed_tests = StudentTest.where(status: "completed", user_id: current_user.id).order("created_at ASC")


        #=end
        render "ceo_index"
      end    
    end
    
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end
  def show 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_alert_class(key)
    key = 'danger' if key == :error or key == "alert"
    key = 'success' if key == "notice"
    alert_class = ["alert"]
    if key.to_s == "fail"
      alert_class << "alert-danger"
    elsif key == :notice
      alert_class << "alert-info"
    else
      alert_class << "alert-#{key}"
    end
    alert_class.join(" ")
  end
end

app/helpers/descriptive_questions_helper.rb
module DescriptiveQuestionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/multiple_choice_questions_helper.rb
module MultipleChoiceQuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
	def get_student_answer(question_id,test_id,question_type)
		student_test_id = StudentTest.where(user_id: current_user.id, test_id: test_id).first.id
		student_answer = StudentAnswer.where(student_test_id: student_test_id, question_type: question_type, question_id: question_id).first.answer
	end	

	def get_student_result(question_id,test_id,question_type)
		student_test_id = StudentTest.where(user_id: current_user.id, test_id: test_id).first.id
		student_answer = StudentAnswer.where(student_test_id: student_test_id, question_type: question_type, question_id: question_id).first.result
	end	

	def get_student_test_result(test_id)
		no_of_correct_answers = StudentTest.where(test_id: test_id, user_id: current_user.id).first.no_of_correct_answers
	end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :EmpId %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>

  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <!-- on change of field i need to get respective lovs for reportee list -->
  <div class="field">
    <%= f.label :department %><br>
    <%= f.select :department, options_for_select(["Select One", "VP", "Director", "Manager", "SDE"],:disabled => ["Select One"]), :class => 'genForm_dropBox' %>

  </div>


  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Salary</th>
      <th>Rating</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.id %></td>
        <td><%= employee.name %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.rating %></td>
        <td><%= employee.department %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @employee.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @employee.rating %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/home/ceo_index.html.erb
<div class="page-header">
  <h2>Tests</h2>
</div>

app/views/home/index.html.erb
<div class="page-header">
 <h1>Listing Employees</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>SeedPod3</title>
  </head>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <body>
    <%= render "shared/banner" %>
    <% if current_user.present?  %>
      <div class="col-md-2">
        <%= render "shared/side_bar" %>
      </div>
      <div class="col-md-10">
        <div class="container">
          <div>
            <section>
              <% flash.each do |key, value| %>
                <div class="<%= flash_alert_class(key) %>" id="div">
                  <button class="close" data={dismiss="alert"} type="button", "aria-hidden".to_sym="true" 
                    &times;>
                  </button>
                  <%= raw value %>
                </div>
              <% end %>
            </section>
          </div>
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner container-fluid">
    <div class="col-sm-12">
      <div class="navbar-header">
        <div class="navbar-brand">
          <%= link_to (image_tag "logo.jpg", :alt => "Logo Here", :height => "41px"), root_path %>
        </div>
      </div>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Home", root_path %>
        </li>
<!--         <li>
          <%#= link_to "About", "#" %>
        </li> -->
        
<!--         <li>
          <%#= link_to "Contact", "#" %>
        </li> -->
        <% if current_user.present? %>
         
            <li><%= link_to "Create Employee", new_employee_path %>
              
            </li>
            <li><%= link_to "List Of Employee", employees_path %>
              
            </li>

                 <li>
            <%= link_to "View Profile", registrations_show_path %>
          </li>

          <li>
            <%= link_to "Sign-Out", destroy_user_session_path, :data => {:method => :delete} %>
          </li>
         
        <% else %>
          <li>
            <%= link_to "Sign-IN", new_user_session_path %>
          </li>
     <!--      <li>
            <%#= link_to "Registration", new_user_registration_path %>
          </li> -->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_employee_side_bar.html.erb
<ul  class="nav navbar-nav">
  
</ul>

app/views/shared/_error_messages.html.erb
<ul class="nav">
  <% object.errors.full_messages.each do |message| %>
    <li class="alert alert-danger">
      <%= message %>
    </li>
  <% end %>
</ul>

app/views/shared/_side_bar.html.erb
<%# if current_user.teacher? %>
<%#= render "shared/teacher_side_bar" %>
 
<%# else %>
   <%#= render "shared/student_side_bar" %>
<%#end %>